title: SQL Engagement Metrics – DAU, MAU, Growth
description: Mini project showcasing core SaaS engagement metrics using SQL on StrataScratch
show_downloads: false
google_analytics: false
markdown: kramdown
